### ISSUE TITLE
Some bugs I found within the stock games on my newly recieved thumby

### ISSUE THREAD

**Issue by DonPanicton** [TinyCircuits/TinyCircuits-Thumby-Games#7] opened 2022-01-11 09:28 UTC
I have no idea if the is the right place to report issues with the stock games on the thumby but it seems kinda fitting here. If not, I am sorry.

I was so lucky to receive one of the 50 early bird units of the thumby and I found some bugs within the pre-installed games (MicroPython v1.17 on 2021-09-02):

SpaceDebris:
when I destroy the last comet the game freezes and i have to make a hard reset. No finish screen whatsoever.

Thumgeon (my favorite game for the thumby so far despite game breaking bugs):
- sometimes it can happen that a dialogue object gets spawned in font of a door which can make further progress impossible (or are those riddles I have to solve before I can proceed?)
- pressing left (on the d-pad) within the inventory (to select the drop action i guess) freezes the game and a hard reset has to be performed
- any interaction with the a shop will cause the game to freeze and I have to perform a hard reset

**Comment by jmtinycircuits** [comment] 2022-01-11 18:59
I'll take a look at this.

When the game freezes there's probably an error message. If you connect to the IDE, focus the terminal panel, and press ctrl+d, the Thumby will boot to the main menu. Play the game until it crashes to see the error.

**Comment by JohnnyRtx** [comment] 2022-01-11 19:06
I have the same issue in emulator, i've been playing there waiting for my Thumby order to be confirmed. Both of these glitch and the TinyMonster game says it is missing "README.MD" module.

**Comment by jmtinycircuits** [comment] 2022-01-11 19:10
Looks like SpaceDebris and Thumgeon had some functions that weren't ported to the newest API and were missing some parameters.

I'll take a lot at the two other problems in Thumgeon.

For TinyMonster, at what point does it show that error?

**Comment by JohnnyRtx** [comment] 2022-01-11 19:12
It shows it while starting the emulation.

**Comment by jmtinycircuits** [comment] 2022-01-11 19:13
You would be able to provide a screenshot?

**Comment by jmtinycircuits** [comment] 2022-01-11 19:36
There is a check to ensure tiles do not block doors, not sure why it is still occurring. In any case, signs will now only spawn in the room center if there's an empty tile.

Look at the last issue.

**Comment by jmtinycircuits** [comment] 2022-01-11 19:40
Inventory issue was also related to a missing parameter.

**Comment by jmtinycircuits** [comment] 2022-01-11 19:57
Arcade and format button have the updated games now.

@JohnnyRtx please open another issue with a screenshot.

Closing.

**Closed by jmtinycircuits** 2022-01-11 19:57 UTC
